version: '3'
services:
  web:
    restart: always
    build: .
    image: prueba
    command: yarn start
    ports:
      - "3000:3000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2000M